### ISSUE TITLE
Missing module './L.Routing.Itinerary'

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/PokeMap-2#47]
Hi guys,
with your latest npm release there seem to be some missing packages. Here's the result of `npm install pokemap-2`.

```
> leaflet-control-geocoder@1.5.2 postinstall /data/code/pokemon/node_modules/pokemap-2/node_modules/leaflet-control-geocoder
> sh ./scripts/build.sh


> pokemap-2@0.2.0 postinstall /data/code/pokemon/node_modules/pokemap-2
> browserify js/pokemap.js -o pokemap.bundle.js -t es6ify -t browserify-css -g browserify-css --standalone PokeMap

Error: Cannot find module './L.Routing.Itinerary' from '/data/code/pokemon/node_modules/pokemap-2/node_modules/leaflet-routing-machine/dist'
    at /data/code/pokemon/node_modules/resolve/lib/async.js:55:21
    at load (/data/code/pokemon/node_modules/resolve/lib/async.js:69:43)
    at onex (/data/code/pokemon/node_modules/resolve/lib/async.js:92:31)
    at /data/code/pokemon/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:117:15)
```

**Comment by farisca** [comment]
I think it's fixed with the new version 0.2.1

**Comment by johartl** [comment]
Unfortunately it's still not working

```
> leaflet-control-geocoder@1.5.2 postinstall /data/code/pokemon/node_modules/pokemap-2/node_modules/leaflet-control-geocoder
> sh ./scripts/build.sh


> pokemap-2@0.2.1 postinstall /data/code/pokemon/node_modules/pokemap-2
> browserify js/pokemap.js -o pokemap.bundle.js -t es6ify -t browserify-css -g browserify-css --standalone PokeMap

Error: Cannot find module './geocoders/nominatim' from '/data/code/pokemon/node_modules/pokemap-2/node_modules/leaflet-control-geocoder/dist'
    at /data/code/pokemon/node_modules/resolve/lib/async.js:55:21
    at load (/data/code/pokemon/node_modules/resolve/lib/async.js:69:43)
    at onex (/data/code/pokemon/node_modules/resolve/lib/async.js:92:31)
    at /data/code/pokemon/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:117:15)
```

You might need to delete your `node_modules` folder to see the effect.

**Comment by sacdallago** [comment]
If you installed it with the `-g` option, then you will never be able to reproduce the error @farisca

**Comment by farisca** [comment]
Ok, so there's a new version - 0.2.2. Hopefully this one fixes the issue

**Comment by johartl** [comment]
It's fixed. Thanks!
